FROM fedora:__FEDORA_VERSION__
MAINTAINER marun@redhat.com

RUN echo 'deltarpm=0' >> /etc/dnf/dnf.conf

RUN dnf -y update; dnf -y install yum-utils findutils; dnf clean all

ADD sync-yum-mirrors.sh /sync-yum-mirrors.sh

CMD ["/sync-yum-mirrors.sh"]
